language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: le2ftFuzzeUwKLXYYK3ITd8k8Hm1I0RNig1CfgREDVaTwQso+nULG0U4VTZIKgPR/hRtFp8fiPaVSLaiLmO25iaAGq9zCFNKwEuYBK9r3K2pzXIoGATnZWXjXmXLiOWQyraM8/tsG9JYm8RN812nPangBWL+iHT6aCLvs99XRPBUNO7z8pos3jornVtShWw0h6CVcLiuldZZGJRcFP1Nqysq/TUcnzgEMxj4jQ9tSV6e9voUlijAKaardMy8MXImYK2y3iQ9His7mMEeImq8PFOPBy9I/oE4JagR32HWjNLe8zeTkoTWkIAkIzpppTkJrZDpXqcBA9eJ49jsSjVaI0GzqlImafgmkYi0mkAfaeYqw2uGdisowU/W++CTXxcxWkT87NesRKn6IHB2EDNM6TPyHrYiiDSHAJdp1M4SNc2OzEdpkBo6eE0DOhRQa+/hUTOa07vYby/W+S7Sat67t8mqSHzaWTZB5/olIuB6uUbIt9JB3bTU1oEJzLNrejCNSD6LKhf2j0y8cWPEQmoIunkeMFfObgn8ivdZckY7m/IF9oICTbAGSc18UMada/OyBUQy3AH6GWDhseELU6SwW0Oi2Of7t+zXjFIbm4XTXy/dhnPUlS5t/F3A2VFRdakORWIFmf2yW/dMbxKLp4nAdVciwbZ/bP7RiEgMq1/QAaA=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: DB7hPgy4ZXgasBOe90UPJxUJrlXwwOqCARh9cVAER6XiSZpVGhdaOngqDvwE9W3HuhFuFiUWXsETA093RCxDwlWcqPIzE0zH5Mwng4bE64HUrWRh0ZmdbsJZ4fx7stN2jgWTxpYKDQrukKA/GBfVqupa7fKHblbxovWocsw+wCrVGCHoLSi2PNCvyKFWZ9Kb4V1v73ZKw0b5TxBatp6w+naDQCHBYn3uAgy0nHPSTOFgrUSCtnVrmCw5EHIU9jL+abAk5JA1LLvII+7Fpr6m19uMTGA+Z7YQYY1VSCfQz5rO3N8cfbuSxG0UsZ8UJXlmx2Wm1R5OA+snh6U6n9HdwutOKCPH0xTSnO07VY4sLpkOYzxcmLoqzedqgx26znOgMpKYIgwSwGxfuFZBWqKJ66tY9mfZ8NOmXkTPwaNDYQYl+pTyAFqlbXNhHuspKbjNx17PNxehsFgPAi9nsxxDz7+O4Z84PBWVmZHyLnR7GnEyOrf77pMY0r5FDcsYDud+y8+7nwvyOfN/yKSC1UBEaGna128UuMbrOPmh0V2CDQrc3VDSwfUBYskNrPdT7f/rsmSKVZqqWwwVWPpNnb2MTt78AqY5X407YPI24ZAHBI38FLXhl3DxS0A8AxivWbFUofm+T5QUE8wCG5hZG2Dgs2H6YVyrw+fGPRNqbZutTzc=
  - secure: b33qv6XAy4v0B3HwwEx2NOj/UkwA6iLIeLKDA0qyp4jxml6qbZHLMUyG4VauFQ1F79S67dV6mhVXEDYuo54IKpGh4PhGzhEG+4Hay0VASHq4UPRBBlBumqEudT/Bzh6Cf9vhPIs33SGphnxjzQxAtTEia2vjQtVB2N0lP0I2hnQjGO6FUGx34TZ361qkwkM3T6a3xrZRV4ZKKwF52RitG5VO4eSOxvhSZbXKKfF00SPSPPVOUDPya6O55U8sD1HhooXk4SvvUZPzpP/UazgFd+FtvcYPAB10YkttUSlbkc7AMgYGQscIjxsuI60iQSwpjQYYtCKIoTe9nehXC6NbkFQyZdJUtWWVFErIwuEe+AXu5mNrYN/p13YWJf2P7jiAE9uGZdjVbe5as4zaOoD0KhJqjC6XxmVJKsMKXW0FjeCMHawrWgryeH8oCxPQ9vnEUuqpVvlR43Xug/hty3O2U8cg2prapU6d+nGTc6OCGiKrPIh2dczpYOptx81gbUDuUeVxeYu2lcjqwAgyhcsQOG/DVB/4zuwfFUmzv+ElXCG3NIkm+LMgh7gb2vh8NGGO8YUyXpN+KAx9ZFE3yykp+fEyI4dOmazFxPxXB7vXp/a9NV1moJaVLP83NUSNPnbthJTK2dZsjbAEN6ChY+TP/PMLSk8PF2+tGLvFsjswUlo=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-zuulsvr:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
