language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: le2ftFuzzeUwKLXYYK3ITd8k8Hm1I0RNig1CfgREDVaTwQso+nULG0U4VTZIKgPR/hRtFp8fiPaVSLaiLmO25iaAGq9zCFNKwEuYBK9r3K2pzXIoGATnZWXjXmXLiOWQyraM8/tsG9JYm8RN812nPangBWL+iHT6aCLvs99XRPBUNO7z8pos3jornVtShWw0h6CVcLiuldZZGJRcFP1Nqysq/TUcnzgEMxj4jQ9tSV6e9voUlijAKaardMy8MXImYK2y3iQ9His7mMEeImq8PFOPBy9I/oE4JagR32HWjNLe8zeTkoTWkIAkIzpppTkJrZDpXqcBA9eJ49jsSjVaI0GzqlImafgmkYi0mkAfaeYqw2uGdisowU/W++CTXxcxWkT87NesRKn6IHB2EDNM6TPyHrYiiDSHAJdp1M4SNc2OzEdpkBo6eE0DOhRQa+/hUTOa07vYby/W+S7Sat67t8mqSHzaWTZB5/olIuB6uUbIt9JB3bTU1oEJzLNrejCNSD6LKhf2j0y8cWPEQmoIunkeMFfObgn8ivdZckY7m/IF9oICTbAGSc18UMada/OyBUQy3AH6GWDhseELU6SwW0Oi2Of7t+zXjFIbm4XTXy/dhnPUlS5t/F3A2VFRdakORWIFmf2yW/dMbxKLp4nAdVciwbZ/bP7RiEgMq1/QAaA=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: bd2Knd+enXI7OslWgwa58NqImmK4ImcH9VX/WuraJAp0MVJSar271M0qJuHqCRZYJXSVFxIJBK9maids/M0LAgUgzE2S01b/zzo8MhHle1dlY58VtD5aAo41rlD1cuW5zPzgCm3u8kkgedUjFbsEc76SAXD3c0ZQLWJKrWwd3OBRxYxG0RgvMlXMV5w6znf5SXaaTP/WkTYT89by5UsuWDeF7jO5YG/XWFJRVamIxhPDHb5LpFnVIH1qWlbwwn+3udypulsqgJzur1Xb9lir9TAWVXTbDgtdReeHeGzlpV6ywebBXjOXE1uTMd+f1AavDp3CuBTDBbx2a4q2PPC5BmI/wyqGxmhUDLUWMqIVDoy7ooKxocz9/1xuw9Qd2X6w+qjYpHqYjGB3S6Kg/6R4wx/f4QaCSFu9o7gE2jlPe+f/PBfdrmFDcpUkqMKsNQGuG6goJ5BXAM9oo+uT9nUsT8IReZjejGBAcVG1Dr39FweUQ8GQM+bYLZ8g0oxx9WUa7E6LXnH61vOy0jsphRzqzzS+nyBQEceVueHMR74p/1vqDpKc0HpSbR5ZATfpCHVeUia+xr56UVxsuur4GTkfV6VvlRPmjpnq+ZFuXldd/gQCqd+5JJa6sXMgIUraSytcjlOjCGf1jmZV7makfa5zC25KBcZsHrmrhaXLr75f2zI=
  - secure: dvw6Jp70NhB4mpLClF7EGu6tb+D4MDfGtYSBkmvcKuxKSuX+rVgqP1X/VEoxTlvsMYxwVvV9K40/qvBvZRG4Fr+TeMhXLZSQgHfei7pZXLV/luZybpUp9MSr7+N+b1YPzoJE8+qiVegHYlhBwEe5HaTzjN613ReqGy+FZs3sOGYrq/vqySlS617Pz9soNX8lx+VhZ948OgsVnJT3gO90rhaETw9y7MLh/i1zn3G9nRMm6eJEnUFnXic9StKrN212ZuLoOl6mSsSh6bfcf2FYBJPD/l5q4nVHqO0D6AaMHIViv9Qj/fRbbF1JpYX3l7vN3ZUsyMnI54TbcYhhuDo3GoEBniiq+jPwzhYZVjYd03rCNRvk5KViLz51nCRBgdsBOPj7RA6p/0bUaghgXTMXwEDPZDQ/uah8E1+OCCbz7q5ZPqz5/RRp6/FudIByiZHZpXXgIp/0YZ0PMnY1cEp7ngtFs6hdcnaR9A2f9UeVoF492KTr1cP7d7cOH1Gpm1m8falHyTRvxd9H9cBkDnOZT0isBZcXfycV6rf41BbePunISa32wECt4j2HsHyTYbhSZ2fOZimdY3sLuQEnbubel9DnToY7TKApb60pthJYtiCttudkmUu1wYNuw+CZC3AnBwlwZVbunuefAEnIv39IOJB2CVQlWFiHql24sdlKv/g=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-zuulsvr:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
