zuulserver:
    image:   anthonydenecheau/scc-zuulsvr:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "5555:5555"
    external_links:
      - localhost:eurekaserver
      - localhost:configserver
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "5555"
      EUREKA_INSTANCE_HOSTNAME: zuulserver
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"